# Generated by Django 3.0.5 on 2020-04-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('firstPhoto', models.TextField(max_length=255)),
                ('secondPhoto', models.TextField(max_length=255)),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
        ),
    ]
