# Generated by Django 3.0.5 on 2020-04-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='firstPhoto',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='secondPhoto',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
