# Generated by Django 3.0.5 on 2020-04-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200407_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='firstPhoto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='secondPhoto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
