# Generated by Django 3.0.5 on 2020-04-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200406_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('phone', models.CharField(max_length=64, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('birthday', models.DateField(verbose_name='Пароль')),
                ('gender', models.CharField(max_length=32, verbose_name='Пол')),
            ],
        ),
    ]
