# Generated by Django 3.0.5 on 2020-04-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200408_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='purchases',
            new_name='purchase',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
    ]
