# Generated by Django 3.0.5 on 2020-04-09 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200408_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='purchase',
            new_name='purchases',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cart'),
        ),
    ]
