# Generated by Django 3.0.5 on 2020-04-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200423_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.IntegerField(blank=True, default=1300),
            preserve_default=False,
        ),
    ]
