# Generated by Django 3.0.5 on 2020-04-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200427_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя кастомного поля')),
                ('description', models.TextField(blank=True, verbose_name='Описание кастомного поля')),
                ('field_type', models.CharField(blank=True, default='Text', max_length=64, verbose_name='Тип кастомного поля')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Значение кастомного поля')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomField')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='custom_fields',
            field=models.ManyToManyField(through='api.CustomFieldValue', to='api.CustomField'),
        ),
    ]
