# Generated by Django 3.0.5 on 2020-04-09 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200407_1528'),
        ('basket', '0005_auto_20200409_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='order_id',
            new_name='orders',
        ),
        migrations.AlterField(
            model_name='basket',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
    ]
