# Generated by Django 3.0.5 on 2020-04-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20200409_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='ordered',
        ),
        migrations.AddField(
            model_name='basket',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
