# Generated by Django 3.0.5 on 2020-04-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_auto_20200409_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name_plural': 'Корзины'},
        ),
        migrations.AddField(
            model_name='basket',
            name='totalWeight',
            field=models.IntegerField(default=0),
        ),
    ]
