# Generated by Django 3.0.5 on 2020-04-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_auto_20200410_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='totalCount',
            field=models.IntegerField(default=0),
        ),
    ]
