# Generated by Django 3.0.5 on 2020-04-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200407_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=2),
        ),
    ]
