# Generated by Django 3.0.5 on 2020-04-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200407_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=12345, max_length=30),
            preserve_default=False,
        ),
    ]
